import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../Component/Header'
import Details from '../Component/Details'
import Gallery from '../Component/Gallery'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Details/>
      <Gallery/>
    </div>
  )
}
